# Generated by Django 2.1.5 on 2020-01-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='auteur',
            field=models.TextField(default='Anonymous'),
        ),
    ]
