# Generated by Django 2.1.5 on 2020-01-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0003_auto_20200101_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
