# Generated by Django 2.1.5 on 2020-01-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0004_livre_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatriceDistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ligne', models.IntegerField()),
                ('id_colonne', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
