# Generated by Django 2.1.5 on 2020-01-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0005_matricedistance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closeness', models.TextField()),
                ('betweenness', models.TextField()),
                ('pagerank', models.TextField()),
            ],
        ),
    ]
