# Generated by Django 2.2.7 on 2020-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0007_auto_20200208_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(default='Anonymous', max_length=300),
        ),
        migrations.AlterField(
            model_name='livre',
            name='language',
            field=models.CharField(default='English', max_length=300),
        ),
    ]
