# Generated by Django 2.1.5 on 2020-01-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_livre_auteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='auteur',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
